### ISSUE TITLE
error with dependencies

### ISSUE THREAD

**Issue by hiperion** [tls-attacker/TLS-Attacker-Project-Template#1]
Hello I'm trying to build the project and I get this issue:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building TLS-Attacker-Template 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.rub.nds.tlsattacker:TLS-Core:jar:2.4 is missing, no dependency information available
[WARNING] The POM for de.rub.nds.tlsattacker:Attacks:jar:2.4 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.343 s
[INFO] Finished at: 2018-02-20T15:45:15+02:00
[INFO] Final Memory: 8M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TLS-Attacker-Template: Could not resolve dependencies for project de.rub.nds.tlstemplate:TLS-Attacker-Template:jar:1.0: The foll
owing artifacts could not be resolved: de.rub.nds.tlsattacker:TLS-Core:jar:2.4, de.rub.nds.tlsattacker:Attacks:jar:2.4: Failure to find de.rub.nds.tlsattacker:TLS-Core:ja
r:2.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or u
pdates are forced -> [Help 1]

**Comment by ic0ns** [comment]
Hey,
you need to install TLS-Attacker 2.4 first.
```
git clone https://github.com/RUB-NDS/TLS-Attacker.git
cd TLS-Attacker
mvn clean install
```

**Comment by hiperion** [comment]
Thanks I made mvn clean package by mistake.
